services:
  frontend:
    image: nareshdockerclient/local-linker-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./client/.env
    depends_on:
      - backend
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
        
  backend:
    image: nareshdockerclient/local-linker-backend:latest
    expose:
      - "4000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  
  redis:
    image: redis:7
    container_name: redis
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge